// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistem_wisata.Data;

#nullable disable

namespace SistemWisata.Migrations
{
    [DbContext(typeof(sistem_wisataContext))]
    [Migration("20241107072948_CreateIdentitySchema")]
    partial class CreateIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("sistem_wisata.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama_Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("sistem_wisata.Models.Lokasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama_Lokasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provinsi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lokasi");
                });

            modelBuilder.Entity("sistem_wisata.Models.Wisata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto_Wisata")
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LokasiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama_Wisata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("LokasiId");

                    b.ToTable("Wisata");
                });

            modelBuilder.Entity("sistem_wisata.Models.Wisata", b =>
                {
                    b.HasOne("sistem_wisata.Models.Kategori", "Kategori")
                        .WithMany("Wisata")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistem_wisata.Models.Lokasi", "Lokasi")
                        .WithMany("Wisata")
                        .HasForeignKey("LokasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Lokasi");
                });

            modelBuilder.Entity("sistem_wisata.Models.Kategori", b =>
                {
                    b.Navigation("Wisata");
                });

            modelBuilder.Entity("sistem_wisata.Models.Lokasi", b =>
                {
                    b.Navigation("Wisata");
                });
#pragma warning restore 612, 618
        }
    }
}
